print("nika dobo")
print("luka gabelaia")
print("aleqsandre kekoshvili")
print("dachi alania")
print("giorgi kacitadze small")
print("giorgi kacitadze n2 big")
print("giorgi tedozashvili")
print("guri dvalishvili")